### ISSUE TITLE
aviutl.exe を外部プロセスから起動すると意図しない場所に ffmpeg_decoder.ini が生成される

### ISSUE THREAD

**Issue by neofuji** [kusaanko/AviUtlFFmpegDecoder#1]
設定ファイルが aviutl.exe のディレクトリではなく以下のディレクトリに生成されることがあるため報告いたします。
`%LOCALAPPDATA%\VirtualStore\Windows\SysWOW64`

**Comment by kusaanko** [comment]
どのような起動をした際にそのようになってしまうのか具体的に教えていただけますか？
作業ディレクトリの関係ですかね？

**Comment by kusaanko** [comment]
とりあえずv0.2をリリースしてみたので試してみてください

**Comment by neofuji** [comment]
.aup ファイルを aviutl.exe に関連付けした状態でエクスプローラーからプロジェクトファイルを開くとこの問題が発生していましたが、v0.2 で修正されたことを確認しました。
迅速な対応ありがとうございます。

**Comment by kusaanko** [comment]
無事正常に動作したみたいでよかったです。
バグ報告ありがとうございました。
